[project]
name = "auto-rorant-creator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "helium>=5.1.2",
    "pyperclip>=1.11.0",
    "requests>=2.32.5",
]
